const mongoose = require('mongoose');

const settingsSchema = new mongoose.Schema({
  institutionName: { type: String, default: 'BIITM Quiz Master' },
  institutionLogo: { type: String, default: '' },
  primaryColor: { type: String, default: '#3b82f6' },
  secondaryColor: { type: String, default: '#10b981' },
  defaultPassPercentage: { type: Number, default: 40 },
  defaultDurationMinutes: { type: Number, default: 60 },
  pdfHeader: { type: String, default: 'BIITM QUIZ MASTER - Secure Online Examination Platform' },
  pdfFooter: { type: String, default: 'Generated by BIITM Quiz Master Admin Portal' }
}, { timestamps: true });

const Settings = mongoose.model('Settings', settingsSchema);

module.exports = Settings;
