import React, { createContext, useContext, useState, useEffect } from 'react';
import api from '../services/api';

const SettingsContext = createContext(null);

export const useSettings = () => {
  const context = useContext(SettingsContext);
  if (!context) {
    throw new Error('useSettings must be used within a SettingsProvider');
  }
  return context;
};

export const SettingsProvider = ({ children }) => {
  const [settings, setSettings] = useState({
    institutionName: 'BIITM Quiz Master',
    institutionLogo: '',
    primaryColor: '#3b82f6',
    secondaryColor: '#10b981',
    defaultPassPercentage: 40,
    defaultDurationMinutes: 60,
    pdfHeader: 'BIITM QUIZ MASTER - Secure Online Examination Platform',
    pdfFooter: 'Generated by BIITM Quiz Master Admin Portal'
  });
  const [loadingSettings, setLoadingSettings] = useState(true);

  useEffect(() => {
    const fetchSettings = async () => {
      try {
        const { data } = await api.get('/settings');
        if (data) {
          setSettings({
            institutionName: data.institutionName || 'BIITM Quiz Master',
            institutionLogo: data.institutionLogo || '',
            primaryColor: data.primaryColor || '#3b82f6',
            secondaryColor: data.secondaryColor || '#10b981',
            defaultPassPercentage: data.defaultPassPercentage || 40,
            defaultDurationMinutes: data.defaultDurationMinutes || 60,
            pdfHeader: data.pdfHeader || 'BIITM QUIZ MASTER - Secure Online Examination Platform',
            pdfFooter: data.pdfFooter || 'Generated by BIITM Quiz Master Admin Portal'
          });
        }
      } catch (err) {
        console.error('Failed to load global settings', err);
      } finally {
        setLoadingSettings(false);
      }
    };
    fetchSettings();
  }, []);

  return (
    <SettingsContext.Provider value={{ settings, loadingSettings }}>
      {children}
    </SettingsContext.Provider>
  );
};
